# Generated by Django 3.0.5 on 2020-12-09 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import judge.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.CharField(default=judge.models.get_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserGroup')),
                ('hosts', models.ManyToManyField(related_name='contest_host_user', to=settings.AUTH_USER_MODEL)),
                ('testers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.CharField(default=judge.models.get_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('inTerms', models.TextField()),
                ('outTerms', models.TextField()),
                ('corCode', models.TextField()),
                ('time_limit', models.IntegerField(default=1)),
                ('examples', models.IntegerField(default=1)),
                ('notice', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('conProbId', models.CharField(default='A', max_length=10)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Contest')),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserGroup')),
            ],
            options={
                'ordering': ['conProbId'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.CharField(default=judge.models.get_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.Contest')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TutorialTopic',
            fields=[
                ('id', models.CharField(default=judge.models.get_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialComment',
            fields=[
                ('id', models.CharField(default=judge.models.get_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.TutorialComment')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Tutorial')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='tutorial',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.TutorialTopic'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.CharField(default=judge.models.get_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('inputs', models.TextField()),
                ('output', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.CharField(default=judge.models.get_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python3'), ('c_cpp', 'C/C++')], max_length=10)),
                ('verdict', models.CharField(default='PJ', max_length=5)),
                ('details', models.TextField(blank=True, null=True)),
                ('time_code', models.CharField(choices=[('BC', 'BC'), ('DC', 'DC'), ('AC', 'AC')], default='BC', max_length=2)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProblemComment',
            fields=[
                ('id', models.CharField(default=judge.models.get_random_id, editable=False, max_length=10, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.ProblemComment')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.Problem')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
