# Generated by Django 3.2.8 on 2021-10-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='checker_func_lang',
            field=models.CharField(blank=True, choices=[('cpp', 'C++'), ('python3', 'Python')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='correct_lang',
            field=models.CharField(blank=True, choices=[('cpp', 'C++'), ('python3', 'Python')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('cpp', 'C++'), ('python3', 'Python')], max_length=10),
        ),
    ]
