# Generated by Django 3.0.5 on 2020-12-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['conProbId', '-date']},
        ),
        migrations.AlterModelOptions(
            name='problemcomment',
            options={'ordering': ['-date']},
        ),
    ]
