# Generated by Django 3.2.8 on 2021-10-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'ordering': ('-problem_char',)},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'ordering': ('-created_at',)},
        ),
    ]
