# Generated by Django 3.2.2 on 2021-06-02 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='details',
        ),
        migrations.AddField(
            model_name='submission',
            name='wrong_tc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judge.testcase'),
        ),
        migrations.CreateModel(
            name='JudgeQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.submission')),
            ],
        ),
    ]
