# Generated by Django 3.2.5 on 2021-07-13 23:33

from django.db import migrations, models
import judge.models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(validators=[judge.models.validate_past]),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(validators=[judge.models.validate_past]),
        ),
    ]
