# Generated by Django 3.2.8 on 2021-10-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20211014_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_cases',
            field=models.ManyToManyField(blank=True, null=True, to='judge.TestCase'),
        ),
    ]
