# Generated by Django 3.2.2 on 2021-05-10 06:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20210506_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('inTerms', models.TextField()),
                ('outTerms', models.TextField()),
                ('corCode', models.TextField()),
                ('checker', models.TextField(blank=True, null=True)),
                ('time_limit', models.IntegerField(default=1)),
                ('memory_limit', models.IntegerField(default=256)),
                ('difficulty', models.IntegerField(default=1500)),
                ('examples', models.IntegerField(default=1)),
                ('notice', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['difficulty', '-date'],
            },
        ),
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_char', models.CharField(default='A', max_length=3)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
        migrations.AddField(
            model_name='contest',
            name='problem',
            field=models.ManyToManyField(through='judge.ContestProblem', to='judge.Problem'),
        ),
    ]
