# Generated by Django 3.2.5 on 2021-07-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20210714_0533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='hidden_till',
        ),
    ]
