# Generated by Django 3.2.8 on 2021-10-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_auto_20211018_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestproblem',
            options={'ordering': ('problem_char',)},
        ),
    ]
