# Generated by Django 3.2.2 on 2021-06-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_problemdiscussion_tutorialdiscussion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemdiscussion',
            options={'ordering': ['-date']},
        ),
    ]
