# Generated by Django 3.2.5 on 2021-07-16 07:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_remove_problem_hidden_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=31, null=True), blank=True, null=True, size=None),
        ),
    ]
