# Generated by Django 3.2.2 on 2021-05-10 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_auto_20210510_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='problem',
            new_name='problems',
        ),
    ]
