# Generated by Django 3.2.2 on 2021-06-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_alter_problemdiscussion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemdiscussion',
            options={'ordering': ['date']},
        ),
    ]
