# Generated by Django 3.2.8 on 2021-10-22 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_auto_20211022_0724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ('created_at',)},
        ),
    ]
