# Generated by Django 3.2.23 on 2024-01-03 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_alter_testcase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='cpu_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='checker_func_lang',
            field=models.CharField(blank=True, choices=[('c_cpp', 'C/C++'), ('python', 'Python'), ('typescript', 'TypeScript'), ('kotlin', 'Kotlin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='correct_lang',
            field=models.CharField(blank=True, choices=[('c_cpp', 'C/C++'), ('python', 'Python'), ('typescript', 'TypeScript'), ('kotlin', 'Kotlin')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('c_cpp', 'C/C++'), ('python', 'Python'), ('typescript', 'TypeScript'), ('kotlin', 'Kotlin')], max_length=10),
        ),
    ]
