# Generated by Django 3.2.2 on 2021-05-10 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0009_problem_hidden_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='hidden_till',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
