# Generated by Django 3.2.2 on 2021-05-10 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ws', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activechannels',
            name='room_name',
        ),
        migrations.AlterField(
            model_name='activechannels',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
