# Generated by Django 3.2.2 on 2021-05-11 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ws', '0002_auto_20210511_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activechannels',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
