POST {{main}}/users/login/
Content-Type: application/json

{ "username" : "robert", "password" : "1234" }

> {% client.global.set('robert_auth', response.body.jwt) %}
###

GET {{main}}/api/test_cases/?problem_id=47
x-auth-token: {{robert_auth}}
Content-Type: application/json

###
POST {{main}}/api/test_cases/?problem_id=47
x-auth-token: {{staff_auth}}
Content-Type: application/json

{
  "problem": 47,
  "inputs": "8\r\n8\r\n4\r\n8\r\n5\r\n1\r\n8\r\n6\r\n9\r\n"
}